In [41]:
import pandas as pd
import numpy as np

In [42]:
socio_eco = pd.read_csv(r'a-fanning-doughnut-v3-a0460e5\Analysis-Final\myData\2_20250108_doughnutv3-data.csv')

In [43]:
socio_eco.head()

,domain,dimension,type,group,indicator,date,populationTotal,GNIperCap,value
0,ecological,climate change,global doughnut,World,co2_ppm,2000,NaN,NaN,368.96
1,ecological,climate change,global doughnut,World,co2_ppm,2001,NaN,NaN,370.57
2,ecological,climate change,global doughnut,World,co2_ppm,2002,NaN,NaN,372.58
3,ecological,climate change,global doughnut,World,co2_ppm,2003,NaN,NaN,375.14
4,ecological,climate change,global doughnut,World,co2_ppm,2004,NaN,NaN,376.95

In [44]:
socio = socio_eco[socio_eco['domain'] == 'social']

In [45]:
socio.head()

,domain,dimension,type,group,indicator,date,populationTotal,GNIperCap,value
1334,social,food,global doughnut,World,undernourishment,2000,6.038540e+09,11037.790569,13.085805
1335,social,food,global doughnut,World,undernourishment,2001,6.118589e+09,11164.291496,13.140674
1336,social,food,global doughnut,World,undernourishment,2002,6.198482e+09,11296.456203,13.177027
1337,social,food,global doughnut,World,undernourishment,2003,6.278159e+09,11566.253778,13.119044
1338,social,food,global doughnut,World,undernourishment,2004,6.358091e+09,12007.379620,12.793242

In [46]:
socio.reset_index(drop=True)

,domain,dimension,type,group,indicator,date,populationTotal,GNIperCap,value
0,social,food,global doughnut,World,undernourishment,2000,6.038540e+09,11037.790569,13.085805
1,social,food,global doughnut,World,undernourishment,2001,6.118589e+09,11164.291496,13.140674
2,social,food,global doughnut,World,undernourishment,2002,6.198482e+09,11296.456203,13.177027
3,social,food,global doughnut,World,undernourishment,2003,6.278159e+09,11566.253778,13.119044
4,social,food,global doughnut,World,undernourishment,2004,6.358091e+09,12007.379620,12.793242
...,...,...,...,...,...,...,...,...,...
2525,social,peace and justice,national aggregate,Top-20,homicideOver5,2018,1.046173e+09,52608.167455,0.038417
2526,social,peace and justice,national aggregate,Top-20,homicideOver5,2019,1.051648e+09,53222.843627,0.038469
2527,social,peace and justice,national aggregate,Top-20,homicideOver5,2020,1.054758e+09,50542.344123,31.888679
2528,social,peace and justice,national aggregate,Top-20,homicideOver5,2021,1.056315e+09,53271.377901,31.945434
2529,social,peace and justice,national aggregate,Top-20,homicideOver5,2022,1.058832e+09,54517.545360,31.991771

In [47]:
socio = socio[socio['type'] != 'national aggregate']

In [48]:
# drop unnecessary columns
socio = socio.drop(columns=['type', 'group', 'populationTotal', 'GNIperCap', 'domain'])

In [49]:
# see state of missing values
socio.isna().sum()

dimension     0
indicator     0
date          0
value        75
dtype: int64

In [50]:
socio = socio[socio['value'].notna()]

In [51]:
socio_ind = (
    socio.sort_values('date')
       .groupby(['dimension', 'indicator'])
       .agg({
           'date': ['first', 'last'],
           'value': ['first', 'last']
       })
)

In [52]:
socio_ind = socio_ind.round(2)
socio_ind = socio_ind.reset_index()
socio_ind

            dimension          indicator  date        value
                                         first  last  first   last
0        connectivity           internet  2000  2022  93.52  35.82
1        connectivity        publicTrans  2020  2020  52.71  52.71
2           education      adultLiteracy  2000  2022  23.13  16.15
3           education    secondarySchool  2000  2022  60.87  36.91
4              energy       energyAccess  2000  2022  21.71   8.51
5              energy       energyIndoor  2000  2022  50.49  25.92
6            equality     genderGapIndex  2000  2022  45.69  34.72
7                food     foodInsecurity  2015  2022  22.24  29.36
8                food   undernourishment  2000  2022  13.09   9.62
9              health           UHCindex  2000  2022  79.05  28.07
10             health        under5death  2000  2022  75.40  42.62
11            housing         urbanSlums  2000  2022  39.71  32.07
12    income and work    societalPoverty  2000  2022  84.92  72.51
13    income and work          youthNEET  2005  2022  24.97  20.31
14  peace and justice  controlCorruption  2005  2022  79.94  74.78
15  peace and justice      homicideOver5  2000  2022  28.45  19.52
16    political voice         govRegimes  2000  2022  46.64  70.76
17    social cohesion              palma  2000  2022  71.33  64.67
18    social cohesion      socialSupport  2005  2022  20.47  23.01
19              water        drinkingH2O  2000  2022  39.31  36.64
20              water         sanitation  2000  2022  66.31  41.17

In [53]:
table_1 = socio_ind[socio_ind['indicator'] != 'EUshare_hzdHealth'].copy()
table_1 = table_1.round(2) # use two decimals like in assignment sheet
table_1

            dimension          indicator  date        value
                                         first  last  first   last
0        connectivity           internet  2000  2022  93.52  35.82
1        connectivity        publicTrans  2020  2020  52.71  52.71
2           education      adultLiteracy  2000  2022  23.13  16.15
3           education    secondarySchool  2000  2022  60.87  36.91
4              energy       energyAccess  2000  2022  21.71   8.51
5              energy       energyIndoor  2000  2022  50.49  25.92
6            equality     genderGapIndex  2000  2022  45.69  34.72
7                food     foodInsecurity  2015  2022  22.24  29.36
8                food   undernourishment  2000  2022  13.09   9.62
9              health           UHCindex  2000  2022  79.05  28.07
10             health        under5death  2000  2022  75.40  42.62
11            housing         urbanSlums  2000  2022  39.71  32.07
12    income and work    societalPoverty  2000  2022  84.92  72.51
13    income and work          youthNEET  2005  2022  24.97  20.31
14  peace and justice  controlCorruption  2005  2022  79.94  74.78
15  peace and justice      homicideOver5  2000  2022  28.45  19.52
16    political voice         govRegimes  2000  2022  46.64  70.76
17    social cohesion              palma  2000  2022  71.33  64.67
18    social cohesion      socialSupport  2005  2022  20.47  23.01
19              water        drinkingH2O  2000  2022  39.31  36.64
20              water         sanitation  2000  2022  66.31  41.17